version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
  vfcommon: voiceflow/common@0.0.2

commands:
  clone_s3_assets:
    steps:
      - run:
          name: Clone s3 assets
          command: |
            aws s3 sync s3://com.voiceflow.ci.assets/alexa ~/project/tests/smokeTest/recordedSessions

jobs:
  test:
    executor: vfcommon/code-test-executor
    steps:
      - checkout
      - vfcommon/install_node_modules
      - vfcommon/setup_dynamodb
      - run:
          name: "Build package"
          command: |
            yarn build
      - run:
          name: "Run tests"
          command: |
            yarn test
      - codecov/upload:
          file: nyc_coverage/lcov.info
      # temp steps
      - vfcommon/install_aws_cli
      - clone_s3_assets
      - run:
          name: Run smoke tests
          command: yarn test:smoke

  build-push-image:
    executor: vfcommon/build-executor
    steps:
      - vfcommon/build_push_image:
          image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/alexa"
          release_pkg: "@voiceflow/alexa"

  deploy-image:
    executor: vfcommon/build-executor
    steps:
      - vfcommon/deploy_image:
          image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/alexa"
          namespace: "voiceflow-v1"
          target: "deployment/alexa"

  build-deploy-dev-env:
    executor: vfcommon/build-executor
    steps:
      - vfcommon/build_deploy_dev_env:
          image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/alexa"
          component: "alexa"
          ssh_key: "31:42:5a:4e:ee:42:40:e6:77:fc:d4:1b:9f:4e:ca:46"

# When should each job run and what are their dependencies?
workflows:
  # Staging
  build-deploy-staging:
    jobs:
      - build-push-image:
          context: dev-test
          filters:
            branches:
              only:
                - staging
      - deploy-image:
          context: dev-test
          requires:
            - build-push-image
          filters:
            branches:
              only:
                - staging

  # Development environments
  build-deploy-environment:
    jobs:
      - build-deploy-dev-env:
          context: dev-test
          filters:
            branches:
              only:
                - /env-.*/

  # Master (production)
  build-deploy-app:
    jobs:
      - test:
          context: dev-test
          filters:
            branches:
              ignore:
                - /env-.*/
                - staging
      - build-push-image:
          context: dev-test
          filters:
            branches:
              only:
                - master
      - deploy-image:
          context: dev-test
          requires:
            - test
            - build-push-image
          filters:
            branches:
              only:
                - master
      - vfcommon/release:
          context: dev-test
          requires:
            - test
          filters:
            branches:
              only: master
